version: '3.1'
services:
    app:
        build:
            context: ./
            dockerfile: docker_app.docker
        volumes:
            - ./:/var/www
        ports:
            - "6093:1337"
        tty: true
        links:
            - database
            - redis_connection
    database:
        command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci"
        image: mysql:8
        environment:
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=covid_test"
        ports:
            - "3036:3306"
    redis_connection:
        image: redis
        ports:
            - "17379:6379"
